#define EXISTING_TABLE	"ERR: EXISTING_TABLE "
#define UNKNOWN_TABLE	"ERR: UNKNOWN_TABLE "

#define EXISTING_COL	"ERR: EXISTING_COL"

#define TYPE_INT		"INT"
#define TYPE_STRING		"STR"

#define UNKNOWN_TYPE	"UNKNOWN_TYPE "
#define CANNOT_CAST		"CANNOT_CAST "
