#define EXISTING_TABLE	"ERR: EXISTING_TABLE "
#define UNKNOWN_TABLE	"ERR: UNKNOWN_TABLE "

#define EXISTING_COL	"ERR: EXISTING_COL "

#define TYPE_INT		"INT"
#define TYPE_STRING		"STR"

#define UNKNOWN_COL		"ERR: UNKNOWN_COL "
#define UNKNOWN_TYPE	"ERR: UNKNOWN_TYPE "
#define CANNOT_CAST		"ERR: CANNOT_CAST "

#define TOO_MUCH_PARAM			"ERR: TOO_MUCH_PARAMS"
#define NOT_ENOUGH_PARAM		"ERR: NOT_ENOUGH_PARAMS"
#define NO_COL_IN_TABLE			"ERR: NO_COL_IN_TABLE "

#define ILLEGAL_NAME			"ERR: ILLEGAL TABLE NAME "
#define ILLEGAL_CHARACTER		"ILLEGAL CHARACTER: "
