#define ADD_KEYWORD 			"ADD"
#define DELETE_KEYWORD 			"DEL"
#define DISPLAY_KEYWORD 		"DISP"

#define TUPLE_KEYWORD 			"TUPLE"
#define TABLE_KEYWORD 			"TABLE"
#define COL_KEYWORD 			"COL"

#define SET_TUPLES_KEYWORD		"TUPLES"
#define SET_TABLES_KEYWORD		"TABLES"
#define SET_COLS_KEWORD			"COLS"

#define QUIT_KEYWORD			"QUIT"

#define ERROR_HEADER			"ERR: "

#define UNKNOWN_KEYWORD			"UNKNOWN_KEYWORD "

#define TOO_MUCH_WORDS			"TOO_MUCH_WORDS"
#define NOT_ENOUGH_WORDS		"NOT_ENOUGH_WORDS"

#define UNKNOWN_TABLE			"UNKNOWN_TABLE "
#define UNKNOWN_COL				"UNKNOWN_COL "
#define UNKNOWN_TYPE			"UNKNOWN_TYPE "

#define EXISTING_TABLE			"EXISTING_TABLE "
#define EXISTING_COL			"EXISTING_COL"

#define CANNOT_CAST				"CANNOT_CAST "
#define TOO_MUCH_PARAM			"TOO_MUCH_PARAMS"
#define NOT_ENOUGH_PARAM		"NOT_ENOUGH_PARAMS"
#define NO_COL_IN_TABLE			"NO_ERROR_IN_TABLE"

typedef void (*DisplayFunc)(char *str);
